### PR TITLE
Saves a lot of CPU by changing the rendering rate

### PR DESCRIPTION
**Pull request by krischerven**
CPU usage averaged 14 - 15% on my computer which is unreasonably high. Now it's more like 4%. You can get lower if you go above 16 ms (2 - 3% at 50 ms) but this seems like a good place to start. Also I restructured the code to be marginally more efficient because its a hot path

### CODE REVIEW

**Review by goulinkh — APPROVED** [review]

**Comment by goulinkh** [comment]
My bad I thought it was in ms

**Comment by krischerven** [comment]
Oh, alright

**Comment by krischerven** [comment]
@goulinkh Are you going to merge this PR

**Comment by goulinkh** [comment]
Yes

**Comment by krischerven** [comment]
Thanks

**Pull request merged**
